<?php

namespace crossborne\ParameterBundle\Entity;

use Doctrine\ORM\EntityRepository;
use crossborne\ParameterBundle\Model\IParametrized;

/**
 * ParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterRepository extends EntityRepository
{
}
