<?php

namespace crossborne\ParameterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParameterValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterValueRepository extends EntityRepository
{
}
